# 项目相关配置
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 4.7.1
  # 版权年份
  copyrightYear: 2021
  # 实例演示开关
  demoEnabled: false
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: D:/IdeaProjects/ruoyi-plus/uploads
  # 获取ip地址开关
  addressEnabled: false

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 80
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5

# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: druid
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: false

# MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.ruoyi.**.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
    # 设置密钥，务必保持唯一性（生成方式，直接拷贝到main运行即可）Base64.encodeToString(CipherUtils.generateNewKey(128, "AES").getEncoded()) （默认启动生成随机秘钥，随机秘钥会导致之前客户端RememberMe Cookie无效，如设置固定秘钥RememberMe Cookie则有效）
    cipherKey: zSyK5Kp6PZAAjlT+eeNMlg==
  session:
    # Session超时时间，-1代表永不过期（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
    # 同一个用户最大会话数，比如2的意思是同一个账号允许最多同时两个人登录（默认-1不限制）
    maxSession: -1
    # 踢出之前登录的/之后登录的用户，默认踢出之前登录的用户
    kickoutAfter: false
  rememberMe:
    # 是否开启记住我
    enabled: true

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true

#前台配置
front:
  #用户注册
  register:
    roleId : 2
    deptId : 110

plugs:
  sysEvent:
    #是否启用系统事件
    enable: true
    #日志记录类型  2记录所有 1记录成功 0 记录失败
    logType: 2
  pv:
    enable: 1
    #all所有页面 include包含urls配置的页面 exclude排除urls配置的页面
    scope: include
    urls: /,/resourceStore,/resourceStore/**,/templateStore,/templateStore/**,/scores,/score/**,/scoreStore,/scoreStore/**,/badge,/badge/**,/segmentStore,/segmentStore/**,/preview/**,/couponCenter,/couponCenter/**,/bugReport,/platform/rank/**,/codeStore,/codeStore/**,/courseStore,/courseStore/**,/docStore,/docStore/**,/audioEffectStore,/audioEffectStore/**,/picStore/wallPater
    #缓存一分钟内相同的请求
    cacheMinute: 1
    serverContextPath: http://localhost
  pageStatics:
    enable: 0
    scope: ${plugs.pv.scope}
    urls: ${plugs.pv.urls}
    #缓存一分钟内相同的请求
    cacheSeconds: 5
    saveDbSeconds: 30
    buildSiteDate: 2018-01-01
  holiday:
    enable: 0
    urls: /,/resourceStore,/resourceStore/**,/templateStore,/templateStore/**,/scores,/score/**,/scoreStore,/scoreStore/**,/badge,/badge/**,/segmentStore,/segmentStore/**,/preview/**,/couponCenter,/couponCenter/**,/bugReport,/platform/rank/**,/codeStore,/codeStore/**,/courseStore,/courseStore/**,/docStore,/docStore/**,/audioEffectStore,/audioEffectStore/**,/picStore/wallPater

third:
  login:
    #引导授权用户绑定本平台用户的url，如果为空，自动创建绑定用户
    to_bind_url: /thirdLogin/bind
    gitee:
      authorize_url: https://gitee.com/oauth/authorize?client_id=[client_id]&redirect_uri=[redirect_uri]&response_type=code&scope=[scope]
      client_id: d6f19be193c9d469c12a2667492936c6e770c622cfcbb379b19b6d37933dfe12
      client_secret: fd0e687ac16bb4b0d84e069ecde66e66bf7fe2e2c571c234477b551a930e0a7c
      redirect_uri: /thirdLogin/gitee/callback?redirect=/resourceStore/user/profile
      scope: user_info
    qq:
      authorize_url: https://graph.qq.com/oauth2.0/authorize?client_id=[client_id]&redirect_uri=[redirect_uri]&response_type=code&scope=[scope]
      client_id: 1103445190
      client_secret: ovWqr550ex06pTGH
      redirect_uri: /thirdLogin/qq/callback?redirect=/index
      scope: user_info
